Traceback (most recent call last):
  File "a.py", line 83, in <module>
  File "a.py", line 67, in getdata
FileNotFoundError: [Errno 2] No such file or directory: '../username.txt'
Traceback (most recent call last):
  File "a.py", line 83, in <module>
  File "a.py", line 67, in getdata
FileNotFoundError: [Errno 2] No such file or directory: '../username.txt'
